@startuml IE
  hide circle
  skinparam linetype ortho
  skinparam roundcorner 20
  skinparam class {
    BackgroundColor White
    ArrowColor Silver
    BorderColor Silver
    FontColor Black
    FontSize 12
  }

  entity "party_role" as party_role {
      **party_role_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "party_identifier_type" as party_identifier_type {
      **party_identifier_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "person_type" as person_type {
      **person_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "contact_type" as contact_type {
      **contact_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "organization_role_type" as organization_role_type {
      **organization_role_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "party" as party {
      **party_id**: INTEGER
    --
    * party_type_id: TEXT
    * party_name: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "party_identifier" as party_identifier {
      **party_identifier_id**: INTEGER
    --
    * identifier_number: TEXT
    * party_identifier_type_id: INTEGER
    * party_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "person" as person {
      **person_id**: INTEGER
    --
    * party_id: INTEGER
    * person_type_id: INTEGER
    * person_first_name: TEXT
    * person_last_name: TEXT
      honorific_prefix: TEXT
      honorific_suffix: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "party_relation" as party_relation {
      **party_relation_id**: INTEGER
    --
    * party_id: INTEGER
    * related_party_id: INTEGER
    * relation_type_id: TEXT
      party_role_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "organization" as organization {
      **organization_id**: INTEGER
    --
    * party_id: INTEGER
    * name: TEXT
    * license: TEXT
    * registration_date: DATE
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "organization_role" as organization_role {
      **organization_role_id**: INTEGER
    --
    * person_id: INTEGER
    * organization_id: INTEGER
    * organization_role_type_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "contact_electronic" as contact_electronic {
      **contact_electronic_id**: INTEGER
    --
    * contact_type_id: INTEGER
    * party_id: INTEGER
    * electronics_details: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "contact_land" as contact_land {
      **contact_land_id**: INTEGER
    --
    * contact_type_id: INTEGER
    * party_id: INTEGER
    * address_line1: TEXT
    * address_line2: TEXT
    * address_zip: TEXT
    * address_city: TEXT
    * address_state: TEXT
    * address_country: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "contract_status" as contract_status {
      **contract_status_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "payment_type" as payment_type {
      **payment_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "periodicity" as periodicity {
      **periodicity_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "boundary_nature" as boundary_nature {
      **boundary_nature_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "time_entry_category" as time_entry_category {
      **time_entry_category_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "raci_matrix_subject" as raci_matrix_subject {
      **raci_matrix_subject_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "skill_nature" as skill_nature {
      **skill_nature_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "skill" as skill {
      **skill_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "organization_role_type" as organization_role_type {
      **organization_role_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "graph" as graph {
      **graph_id**: INTEGER
    --
    * graph_nature_id: INTEGER
    * name: TEXT
      description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "boundary" as boundary {
      **boundary_id**: INTEGER
    --
      parent_boundary_id: INTEGER
    * graph_id: INTEGER
    * boundary_nature_id: INTEGER
    * name: TEXT
      description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "host" as host {
      **host_id**: INTEGER
    --
    * host_name: TEXT
      description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "host_boundary" as host_boundary {
      **host_boundary_id**: INTEGER
    --
    * host_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "asset_status" as asset_status {
      **asset_status_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "asset_service_status" as asset_service_status {
      **asset_service_status_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "asset_type" as asset_type {
      **asset_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "assignment" as assignment {
      **assignment_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "raci_matrix" as raci_matrix {
      **raci_matrix_id**: INTEGER
    --
    * asset: TEXT
    * responsible: TEXT
    * accountable: TEXT
    * consulted: TEXT
    * informed: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "raci_matrix_subject_boundary" as raci_matrix_subject_boundary {
      **raci_matrix_subject_boundary_id**: INTEGER
    --
    * boundary_id: INTEGER
    * raci_matrix_subject_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "raci_matrix_activity" as raci_matrix_activity {
      **raci_matrix_activity_id**: INTEGER
    --
    * activity: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "asset" as asset {
      **asset_id**: INTEGER
    --
    * organization_id: INTEGER
      asset_retired_date: DATE
    * asset_status_id: INTEGER
    * asset_tag: TEXT
    * name: TEXT
    * description: TEXT
    * asset_type_id: INTEGER
    * asset_workload_category: TEXT
    * assignment_id: INTEGER
    * barcode_or_rfid_tag: TEXT
      installed_date: DATE
      planned_retirement_date: DATE
      purchase_delivery_date: DATE
      purchase_order_date: DATE
      purchase_request_date: DATE
    * serial_number: TEXT
    * tco_amount: TEXT
    * tco_currency: TEXT
      criticality: TEXT
      asymmetric_keys_encryption_enabled: TEXT
      cryptographic_key_encryption_enabled: TEXT
      symmetric_keys_encryption_enabled: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "asset_service" as asset_service {
      **asset_service_id**: INTEGER
    --
    * asset_id: INTEGER
    * name: TEXT
    * description: TEXT
    * asset_service_status_id: INTEGER
    * port: TEXT
    * experimental_version: TEXT
    * production_version: TEXT
    * latest_vendor_version: TEXT
    * resource_utilization: TEXT
    * log_file: TEXT
    * url: TEXT
    * vendor_link: TEXT
      installation_date: DATE
    * criticality: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "vulnerability_source" as vulnerability_source {
      **vulnerability_source_id**: INTEGER
    --
    * short_code: TEXT
    * source_url: TEXT
    * description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "vulnerability" as vulnerability {
      **vulnerability_id**: INTEGER
    --
    * short_name: TEXT
    * source_id: INTEGER
    * affected_software: TEXT
    * reference: TEXT
    * status_id: TEXT
    * patch_availability: TEXT
    * severity_id: TEXT
    * solutions: TEXT
    * description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "threat_source" as threat_source {
      **threat_source_id**: INTEGER
    --
    * title: TEXT
    * identifier: TEXT
    * threat_source_type_id: INTEGER
    * source_of_information: TEXT
    * capability: TEXT
    * intent: TEXT
    * targeting: TEXT
    * description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "threat_event" as threat_event {
      **threat_event_id**: INTEGER
    --
    * title: TEXT
    * threat_source_id: INTEGER
    * asset_id: INTEGER
    * identifier: TEXT
    * threat_event_type_id: INTEGER
    * event_classification: TEXT
    * source_of_information: TEXT
    * description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "asset_risk" as asset_risk {
      **asset_risk_id**: INTEGER
    --
    * asset_risk_type_id: INTEGER
    * asset_id: INTEGER
    * threat_event_id: INTEGER
      relevance_id: TEXT
      likelihood_id: TEXT
    * impact: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "security_impact_analysis" as security_impact_analysis {
      **security_impact_analysis_id**: INTEGER
    --
    * vulnerability_id: INTEGER
    * asset_risk_id: INTEGER
    * risk_level_id: TEXT
    * impact_level_id: TEXT
    * existing_controls: TEXT
    * priority_id: TEXT
    * reported_date: DATE
    * reported_by_id: INTEGER
    * responsible_by_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "impact_of_risk" as impact_of_risk {
      **impact_of_risk_id**: INTEGER
    --
    * security_impact_analysis_id: INTEGER
    * impact: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "proposed_controls" as proposed_controls {
      **proposed_controls_id**: INTEGER
    --
    * security_impact_analysis_id: INTEGER
    * controls: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "billing" as billing {
      **billing_id**: INTEGER
    --
    * purpose: TEXT
    * bill_rate: TEXT
    * period: TEXT
    * effective_from_date: TIMESTAMP
    * effective_to_date: TEXT
    * prorate: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "scheduled_task" as scheduled_task {
      **scheduled_task_id**: INTEGER
    --
    * description: TEXT
    * task_date: TIMESTAMP
    * reminder_date: TIMESTAMP
    * assigned_to: TEXT
    * reminder_to: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "timesheet" as timesheet {
      **timesheet_id**: INTEGER
    --
    * date_of_work: TIMESTAMP
    * is_billable_id: INTEGER
    * number_of_hours: INTEGER
    * time_entry_category_id: INTEGER
    * timesheet_summary: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "certificate" as certificate {
      **certificate_id**: INTEGER
    --
    * certificate_name: TEXT
    * short_name: TEXT
    * certificate_category: TEXT
    * certificate_type: TEXT
    * certificate_authority: TEXT
    * validity: TEXT
      expiration_date: TIMESTAMP
    * domain_name: TEXT
    * key_size: INTEGER
    * path: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "device" as device {
      **device_id**: INTEGER
    --
    * device_name: TEXT
    * short_name: TEXT
    * barcode: TEXT
    * model: TEXT
    * serial_number: TEXT
    * firmware: TEXT
    * data_center: TEXT
    * location: TEXT
    * purpose: TEXT
    * description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "security_incident_response_team" as security_incident_response_team {
      **security_incident_response_team_id**: INTEGER
    --
      training_subject_id: INTEGER
    * person_id: INTEGER
    * organization_id: INTEGER
      training_status_id: INTEGER
      attended_date: DATE
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "awareness_training" as awareness_training {
      **awareness_training_id**: INTEGER
    --
    * training_subject_id: INTEGER
    * person_id: INTEGER
    * organization_id: INTEGER
    * training_status_id: INTEGER
    * attended_date: DATE
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "rating" as rating {
      **rating_id**: INTEGER
    --
    * author_id: INTEGER
    * rating_given_to_id: INTEGER
    * rating_value_id: INTEGER
      best_rating_id: INTEGER
    * rating_explanation: TEXT
    * review_aspect: TEXT
      worst_rating_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "note" as note {
      **note_id**: INTEGER
    --
    * party_id: INTEGER
    * note: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "threat_source_type" as threat_source_type {
      **threat_source_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "threat_event_type" as threat_event_type {
      **threat_event_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "calendar_period" as calendar_period {
      **calendar_period_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "tracking_period" as tracking_period {
      **tracking_period_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "audit_assertion" as audit_assertion {
      **audit_assertion_id**: INTEGER
    --
    * auditor_type_id: TEXT
    * audit_purpose_id: INTEGER
    * auditor_org_id: INTEGER
    * auditor_person_id: INTEGER
    * auditor_status_type_id: INTEGER
    * scf_identifier: TEXT
    * auditor_notes: TEXT
    * auditor_artifacts: TEXT
    * assertion_name: TEXT
    * assertion_description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "contract" as contract {
      **contract_id**: INTEGER
    --
    * contract_from_id: INTEGER
    * contract_to_id: INTEGER
      contract_status_id: INTEGER
    * document_reference: TEXT
      payment_type_id: INTEGER
      periodicity_id: INTEGER
    * start_date: TIMESTAMP
      end_date: TIMESTAMP
      contract_type_id: INTEGER
      date_of_last_review: TIMESTAMP
      date_of_next_review: TIMESTAMP
      date_of_contract_review: TIMESTAMP
      date_of_contract_approval: TIMESTAMP
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "risk_register" as risk_register {
      **risk_register_id**: INTEGER
    --
    * description: TEXT
    * risk_subject_id: INTEGER
    * risk_type_id: INTEGER
    * impact_to_the_organization: TEXT
      rating_likelihood_id: INTEGER
      rating_impact_id: INTEGER
      rating_overall_risk_id: INTEGER
    * controls_in_place: TEXT
    * control_effectivenes: INTEGER
      over_all_residual_risk_rating_id: INTEGER
    * mitigation_further_actions: TEXT
    * control_monitor_mitigation_actions_tracking_strategy: TEXT
      control_monitor_action_due_date: DATE
    * control_monitor_risk_owner_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "incident" as incident {
      **incident_id**: INTEGER
    --
    * title: TEXT
    * incident_date: DATE
    * time_and_time_zone: TIMESTAMP
    * asset_id: INTEGER
    * category_id: INTEGER
    * sub_category_id: INTEGER
    * severity_id: TEXT
      priority_id: TEXT
      internal_or_external_id: INTEGER
    * location: TEXT
    * it_service_impacted: TEXT
    * impacted_modules: TEXT
    * impacted_dept: TEXT
    * reported_by_id: INTEGER
    * reported_to_id: INTEGER
    * brief_description: TEXT
    * detailed_description: TEXT
    * assigned_to_id: INTEGER
      assigned_date: DATE
    * investigation_details: TEXT
    * containment_details: TEXT
    * eradication_details: TEXT
    * business_impact: TEXT
    * lessons_learned: TEXT
      status_id: INTEGER
      closed_date: DATE
      reopened_time: TIMESTAMP
    * feedback_from_business: TEXT
    * reported_to_regulatory: TEXT
      report_date: DATE
      report_time: TIMESTAMP
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "incident_root_cause" as incident_root_cause {
      **incident_root_cause_id**: INTEGER
    --
      incident_id: INTEGER
    * source: TEXT
    * description: TEXT
      probability_id: TEXT
    * testing_analysis: TEXT
    * solution: TEXT
      likelihood_of_risk_id: TEXT
    * modification_of_the_reported_issue: TEXT
    * testing_for_modified_issue: TEXT
    * test_results: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "raci_matrix_assignment" as raci_matrix_assignment {
      **raci_matrix_assignment_id**: INTEGER
    --
    * person_id: INTEGER
    * subject_id: INTEGER
    * activity_id: INTEGER
    * raci_matrix_assignment_nature_id: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "person_skill" as person_skill {
      **person_skill_id**: INTEGER
    --
    * person_id: INTEGER
    * skill_nature_id: INTEGER
    * skill_id: INTEGER
    * proficiency_scale_id: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "key_performance" as key_performance {
      **key_performance_id**: INTEGER
    --
    * title: TEXT
    * description: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "key_performance_indicator" as key_performance_indicator {
      **key_performance_indicator_id**: INTEGER
    --
    * key_performance_id: INTEGER
    * asset_id: INTEGER
    * calendar_period_id: INTEGER
    * kpi_comparison_operator_id: TEXT
    * kpi_context: TEXT
    * kpi_lower_threshold_critical: TEXT
    * kpi_lower_threshold_major: TEXT
    * kpi_lower_threshold_minor: TEXT
    * kpi_lower_threshold_ok: TEXT
    * kpi_lower_threshold_warning: TEXT
    * kpi_measurement_type_id: TEXT
    * kpi_status_id: TEXT
    * kpi_threshold_critical: TEXT
    * kpi_threshold_major: TEXT
    * kpi_threshold_minor: TEXT
    * kpi_threshold_ok: TEXT
    * kpi_threshold_warning: TEXT
    * kpi_unit_of_measure: TEXT
    * kpi_value: TEXT
    * score: TEXT
    * tracking_period_id: INTEGER
    * trend_id: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "key_risk" as key_risk {
      **key_risk_id**: INTEGER
    --
    * title: TEXT
    * description: TEXT
      base_value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "key_risk_indicator" as key_risk_indicator {
      **key_risk_indicator_id**: INTEGER
    --
    * key_risk_id: INTEGER
    * entry_date: DATE
      entry_value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "assertion" as assertion {
      **assertion_id**: INTEGER
    --
    * foreign_integration: TEXT
    * assertion: TEXT
    * assertion_explain: TEXT
      assertion_expires_on: DATE
    * assertion_expires_poam: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "attestation" as attestation {
      **attestation_id**: INTEGER
    --
    * assertion_id: INTEGER
    * person_id: INTEGER
    * attestation: TEXT
    * attestation_explain: TEXT
    * attested_on: DATE
      expires_on: DATE
      boundary_id: INTEGER
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "attestation_evidence" as attestation_evidence {
      **attestation_evidence_id**: INTEGER
    --
    * attestation_id: INTEGER
    * evidence_nature: TEXT
    * evidence_summary_markdown: TEXT
    * url: TEXT
    * content: TEXT
    * attachment: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "training_subject" as training_subject {
      **training_subject_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "status_value" as status_value {
      **status_value_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "rating_value" as rating_value {
      **rating_value_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "contract_type" as contract_type {
      **contract_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "graph_nature" as graph_nature {
      **graph_nature_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "risk_subject" as risk_subject {
      **risk_subject_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "risk_type" as risk_type {
      **risk_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "incident_category" as incident_category {
      **incident_category_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "incident_sub_category" as incident_sub_category {
      **incident_sub_category_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "incident_type" as incident_type {
      **incident_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "incident_status" as incident_status {
      **incident_status_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "asset_risk_type" as asset_risk_type {
      **asset_risk_type_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "audit_purpose" as audit_purpose {
      **audit_purpose_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  entity "audit_status" as audit_status {
      **audit_status_id**: INTEGER
    --
    * code: TEXT
    * value: TEXT
      created_at: TIMESTAMP
      created_by: TEXT
      updated_at: TIMESTAMP
      updated_by: TEXT
      deleted_at: TIMESTAMP
      deleted_by: TEXT
      activity_log: TEXT
  }

  party_identifier_type |o..o{ party_identifier
  party |o..o{ party_identifier
  party |o..o{ person
  person_type |o..o{ person
  party |o..o{ party_relation
  party |o..o{ party_relation
  party_role |o..o{ party_relation
  party |o..o{ organization
  person |o..o{ organization_role
  organization |o..o{ organization_role
  organization_role_type |o..o{ organization_role
  contact_type |o..o{ contact_electronic
  party |o..o{ contact_electronic
  contact_type |o..o{ contact_land
  party |o..o{ contact_land
  graph_nature |o..o{ graph
  boundary |o..o{ boundary
  graph |o..o{ boundary
  boundary_nature |o..o{ boundary
  host |o..o{ host_boundary
  boundary |o..o{ raci_matrix_subject_boundary
  raci_matrix_subject |o..o{ raci_matrix_subject_boundary
  organization |o..o{ asset
  asset_status |o..o{ asset
  asset_type |o..o{ asset
  assignment |o..o{ asset
  asset |o..o{ asset_service
  asset_service_status |o..o{ asset_service
  vulnerability_source |o..o{ vulnerability
  threat_source_type |o..o{ threat_source
  threat_source |o..o{ threat_event
  asset |o..o{ threat_event
  threat_event_type |o..o{ threat_event
  asset_risk_type |o..o{ asset_risk
  asset |o..o{ asset_risk
  threat_event |o..o{ asset_risk
  vulnerability |o..o{ security_impact_analysis
  asset_risk |o..o{ security_impact_analysis
  person |o..o{ security_impact_analysis
  person |o..o{ security_impact_analysis
  security_impact_analysis |o..o{ impact_of_risk
  security_impact_analysis |o..o{ proposed_controls
  status_value |o..o{ timesheet
  time_entry_category |o..o{ timesheet
  training_subject |o..o{ security_incident_response_team
  person |o..o{ security_incident_response_team
  organization |o..o{ security_incident_response_team
  status_value |o..o{ security_incident_response_team
  training_subject |o..o{ awareness_training
  person |o..o{ awareness_training
  organization |o..o{ awareness_training
  status_value |o..o{ awareness_training
  person |o..o{ rating
  organization |o..o{ rating
  rating_value |o..o{ rating
  rating_value |o..o{ rating
  rating_value |o..o{ rating
  party |o..o{ note
  audit_purpose |o..o{ audit_assertion
  organization |o..o{ audit_assertion
  person |o..o{ audit_assertion
  audit_status |o..o{ audit_assertion
  party |o..o{ contract
  party |o..o{ contract
  contract_status |o..o{ contract
  payment_type |o..o{ contract
  periodicity |o..o{ contract
  contract_type |o..o{ contract
  risk_subject |o..o{ risk_register
  risk_type |o..o{ risk_register
  rating_value |o..o{ risk_register
  rating_value |o..o{ risk_register
  rating_value |o..o{ risk_register
  rating_value |o..o{ risk_register
  person |o..o{ risk_register
  asset |o..o{ incident
  incident_category |o..o{ incident
  incident_sub_category |o..o{ incident
  incident_type |o..o{ incident
  person |o..o{ incident
  person |o..o{ incident
  person |o..o{ incident
  incident_status |o..o{ incident
  incident |o..o{ incident_root_cause
  person |o..o{ raci_matrix_assignment
  raci_matrix_subject |o..o{ raci_matrix_assignment
  raci_matrix_activity |o..o{ raci_matrix_assignment
  person |o..o{ person_skill
  skill_nature |o..o{ person_skill
  skill |o..o{ person_skill
  key_performance |o..o{ key_performance_indicator
  asset |o..o{ key_performance_indicator
  calendar_period |o..o{ key_performance_indicator
  tracking_period |o..o{ key_performance_indicator
  key_risk |o..o{ key_risk_indicator
  assertion |o..o{ attestation
  person |o..o{ attestation
  boundary |o..o{ attestation
  attestation |o..o{ attestation_evidence
@enduml